Add TEST_EXIT_CODE_SKIPPED etc.
picolibc/picolibc pull request #135
Opened 2021-06-13 10:54 UTC by rdiez

When writing tests, one could be mistaken for thinking that any non-zero exit status code is a valid failure indication.
Perhaps we should add:
  #define TEST_EXIT_CODE_FAILURE 1
and then make all tests exit with exactly that code.
Or perhaps add a few constants like TEST_EXIT_CODE_FAILURE_1, TEST_EXIT_CODE_FAILURE_2, ...
Are using the exact test failure exit codes (like 1 or 2) for some other purpose?

2021-06-13 21:32 UTC, keith-packard requested changes
Let's stick this new file in newlib/testsuite/include and then plan on switching the newlib tests to using these definitions too. We would then add that directory to the include path to avoid needing complicated #include directives in each C file.

2021-06-14 06:55 UTC, rdiez commented
What should we do about TEST_EXIT_CODE_FAILURE? Some tests return different failure codes.

2021-06-14 15:21 UTC, keith-packard commented
> What should we do about TEST_EXIT_CODE_FAILURE? Some tests return different failure codes.

I'd say that they should eventually be fixed to use the new macro values. You shouldn't feel any obligation to go through them all and fix them though it would be awesome if you did.

2023-01-16 11:41 UTC, rdiez commented
I'm afraid I haven't got the time at the moment to further pursue this subject.

2023-01-16 11:41 UTC, closed without merging