Detect support for _Complex
picolibc/picolibc pull request #55
Opened 2020-09-01 11:28 UTC by archi

Check if the compiler supports _Complex. If not, disable building `libm/complex/` and disable the `complex.h` header.

2020-09-01 13:44 UTC, archi commented
The two fails here seem to be some travis hiccup?

2020-09-02 20:24 UTC, keith-packard requested changes
Changes look pretty good; let's make it so 'complex.h' doesn't get installed so that applications won't accidentally use it.

2020-09-02 20:24 UTC, keith-packard commented on newlib/libc/include/complex.h
> +#ifdef HAVE_COMPLEX
We shouldn't need changes in this file, but we should change the build system to not install it.

2020-09-14 18:39 UTC, keith-packard commented
All merged in

2020-09-14 18:39 UTC, closed without merging