tinystdio: Add stderr as separate buffer
picolibc/picolibc pull request #675
Opened 2024-01-17 21:45 UTC by zyedidia

Currently stderr is aliased to stdout. This PR adds stderr as a separate file with fd 2. I can put this behind a configuration option if you'd like. Thanks!

2024-01-17 22:04 UTC, keith-packard reviewed
Hrm. This seems like a good plan in general. Would it make sense to split these into separate files so that an application would only end up including those in use? (yeah, --gc-sections helps, but splitting is also useful).

2024-01-17 22:08 UTC, keith-packard commented
Wonder if there's some linker trick we could use to alias stderr to stdout at link time? Having to allocate an extra buffer when you end up using both outputs which are then merged in the OS seems like something it would be good to avoid. But, the current plan seems like it will surprise people who do have them separated, so that needs to get fixed.

2024-01-17 22:27 UTC, keith-packard commented
I pushed a fixup to initialize the stderr lock in `posix_init`; feel free to squash that in. However, thinking about it a bit more, it's pretty clear that we should split posixiob .c into three separate files with three separate constructors and destructors. With that, applications would end up having only the FILEs they used. *and*, we could add `--defsym=stderr=stdout` during link to merge stderr and stdout together.

2024-01-17 22:28 UTC, keith-packard requested changes

2024-01-17 22:28 UTC, keith-packard commented on newlib/libc/tinystdio/posixiob.c
> +static struct __file_bufio __stderr = FDEV_SETUP_POSIX(2, write_buf, BUFSIZ, __SWR, __BLBF);
Need a separate buffer for stderr, but it doesn't have to be BUFSIZ bytes, it could be as small as a single byte.

2024-01-17 23:05 UTC, zyedidia commented
Sounds good, I have split the file into three. Let me how it looks now.

2024-01-18 00:25 UTC, keith-packard approved these changes
This looks fabulous! I'll see if I can figure out why CI didn't test it ...

2024-01-18 00:28 UTC, keith-packard commented
I squashed the commits together and re-pushed them; looks like CI is willing to run now. *shrug*.

2024-01-18 06:05 UTC, merged