vfscanf: Fix pointer step for `wchar_t` specifers `l` followed by `c` or `s` or `[`
picolibc/picolibc pull request #769
Opened 2024-07-10 13:19 UTC by Abdallahs70

Part 7.19.6.2 of C standard states that `fscanf` that a following `c, s, or [` conversion specifier ,to `l`, applies to an argument with type pointer to `wchar_t`.

`WIDE_CHARS` guard is removed  in some occurrences as it prevents the right flow for the function which is taking `wchar_t` pointer step whenever flag `FL_LONG` is set within flags variable.

2024-07-10 16:23 UTC, keith-packard commented
Fix looks reasonable, but we'll need to add a test case to verify that it works correctly.

2024-07-10 20:44 UTC, keith-packard requested changes
Please add a couple of test cases. I think you can add to test/libc-testsuite/sscanf.c

2024-07-17 11:38 UTC, Abdallahs70 commented
testcase is added to test `%lc`, `%ls` and `%l[char-sequence]`

2024-07-18 00:12 UTC, keith-packard commented
I've been digging into this and it's a lot deeper than it appears. There is no support for multi-byte character strings in either vfprintf or vfscanf. I've got fixes for vfprintf ready, and should have the vfscanf fixes ready shortly. I'll post a PR with both of those. That will also address the issue identified here, as that's just one aspect of this larger issue.

2024-07-20 04:21 UTC, closed without merging