Initial LoongArch support
picolibc/picolibc pull request #898
Opened 2024-12-22 22:23 UTC by FlyGoat

Hi All,

This PR implemented initial support for LoongArch.
Currently, only LoongArch 64 build is supported as LoongArch32 ABI is not ratified yet.

It requires a custom `loongarch64-unknown-elf` toolchain to build, my `ct-ng` config built for current crosstool-ng master:
```
CT_CONFIG_VERSION="4"
CT_EXPERIMENTAL=y
CT_ARCH_LOONGARCH=y
# CT_DEMULTILIB is not set
CT_ARCH_USE_MMU=y
CT_ARCH_ARCH="loongarch64"
CT_LIBC_NONE=y
CT_CC_GCC_LIBSTDCXX_VERBOSE=m
CT_CC_LANG_CXX=y
CT_DEBUG_GDB=y
# CT_GDB_CROSS_PYTHON is not set
CT_GETTEXT_NEEDED=y
```

For QEMU testing, a patch to enable semihosting is also required:
https://lore.kernel.org/qemu-devel/20241222-semihosting-v1-1-8a770df60e9c@flygoat.com/

All tests are passing on my side:
```
ninja test
[0/1] Running all tests.
  1/206 picolibc:headers / check-cdef-semihost.h                    OK               0.05s
  2/206 picolibc:headers / check-cdef-stdio.h                       OK               0.05s
  3/206 picolibc:headers / check-cdef-stdio-bufio.h                 OK               0.05s
  4/206 picolibc:headers / check-cdef-sys-auxv.h                    OK               0.05s
  5/206 picolibc:headers / check-cdef-sys-cdefs.h                   OK               0.05s
  6/206 picolibc:headers / check-cdef-sys-errno.h                   OK               0.04s
  7/206 picolibc:headers / check-cdef-sys-fcntl.h                   OK               0.04s
  8/206 picolibc:headers / check-cdef-sys-file.h                    OK               0.04s
  9/206 picolibc:headers / check-cdef-sys-iconvnls.h                OK               0.03s
 10/206 picolibc:headers / check-cdef-sys-lock.h                    OK               0.03s
 11/206 picolibc:headers / check-cdef-sys-param.h                   OK               0.03s
 12/206 picolibc:headers / check-cdef-sys-queue.h                   OK               0.03s
 13/206 picolibc:headers / check-cdef-sys-dir.h                     OK               0.09s
 14/206 picolibc:headers / check-cdef-sys-resource.h                OK               0.07s
 15/206 picolibc:headers / check-cdef-sys-sched.h                   OK               0.07s
 16/206 picolibc:headers / check-cdef-sys-select.h                  OK               0.08s
 17/206 picolibc:headers / check-cdef-sys-stat.h                    OK               0.07s
 18/206 picolibc:headers / check-cdef-sys-syslimits.h               OK               0.07s
 19/206 picolibc:headers / check-cdef-sys-timeb.h                   OK               0.06s
 20/206 picolibc:headers / check-cdef-sys-time.h                    OK               0.06s
 21/206 picolibc:headers / check-cdef-sys-times.h                   OK               0.06s
 22/206 picolibc:headers / check-cdef-sys-timespec.h                OK               0.06s
 23/206 picolibc:headers / check-cdef-sys-types.h                   OK               0.05s
 24/206 picolibc:headers / check-cdef-sys-unistd.h                  OK               0.05s
 25/206 picolibc:headers / check-cdef-sys-utime.h                   OK               0.05s
 26/206 picolibc:headers / check-cdef-sys-wait.h                    OK               0.04s
 27/206 picolibc:headers / check-cdef-rpc-types.h                   OK               0.04s
 28/206 picolibc:headers / check-cdef-sys-tree.h                    OK               0.09s
 29/206 picolibc:headers / check-cdef-rpc-xdr.h                     OK               0.07s
 30/206 picolibc:headers / check-cdef-arpa-inet.h                   OK               0.08s
 31/206 picolibc:headers / check-cdef-alloca.h                      OK               0.07s
 32/206 picolibc:headers / check-cdef-argz.h                        OK               0.07s
 33/206 picolibc:headers / check-cdef-ar.h                          OK               0.07s
 34/206 picolibc:headers / check-cdef-assert.h                      OK               0.06s
 35/206 picolibc:headers / check-cdef-byteswap.h                    OK               0.06s
 36/206 picolibc:headers / check-cdef-ctype.h                       OK               0.06s
 37/206 picolibc:headers / check-cdef-devctl.h                      OK               0.05s
 38/206 picolibc:headers / check-cdef-elf.h                         OK               0.05s
 39/206 picolibc:headers / check-cdef-endian.h                      OK               0.05s
 40/206 picolibc:headers / check-cdef-envlock.h                     OK               0.04s
 41/206 picolibc:headers / check-cdef-envz.h                        OK               0.04s
 42/206 picolibc:headers / check-cdef-errno.h                       OK               0.04s
 43/206 picolibc:headers / check-cdef-dirent.h                      OK               0.09s
 44/206 picolibc:headers / check-cdef-fastmath.h                    OK               0.07s
 45/206 picolibc:headers / check-cdef-fcntl.h                       OK               0.06s
 46/206 picolibc:headers / check-cdef-fenv.h                        OK               0.07s
 47/206 picolibc:headers / check-cdef-fnmatch.h                     OK               0.07s
 48/206 picolibc:headers / check-cdef-getopt.h                      OK               0.07s
 49/206 picolibc:headers / check-cdef-glob.h                        OK               0.07s
 50/206 picolibc:headers / check-cdef-grp.h                         OK               0.07s
 51/206 picolibc:headers / check-cdef-iconv.h                       OK               0.06s
 52/206 picolibc:headers / check-cdef-ieeefp.h                      OK               0.06s
 53/206 picolibc:headers / check-cdef-inttypes.h                    OK               0.06s
 54/206 picolibc:headers / check-cdef-langinfo.h                    OK               0.06s
 55/206 picolibc:headers / check-cdef-libgen.h                      OK               0.05s
 56/206 picolibc:headers / check-cdef-limits.h                      OK               0.05s
 57/206 picolibc:headers / check-cdef-locale.h                      OK               0.05s
 58/206 picolibc:headers / check-cdef-malloc.h                      OK               0.05s
 59/206 picolibc:headers / check-cdef-math.h                        OK               0.07s
 60/206 picolibc:headers / check-cdef-memory.h                      OK               0.07s
 61/206 picolibc:headers / check-cdef-ndbm.h                        OK               0.08s
 62/206 picolibc:headers / check-cdef-pwd.h                         OK               0.08s
 63/206 picolibc:headers / check-cdef-regex.h                       OK               0.08s
 64/206 picolibc:headers / check-cdef-sched.h                       OK               0.08s
 65/206 picolibc:headers / check-cdef-search.h                      OK               0.08s
 66/206 picolibc:headers / check-cdef-setjmp.h                      OK               0.07s
 67/206 picolibc:headers / check-cdef-signal.h                      OK               0.07s
 68/206 picolibc:headers / check-cdef-spawn.h                       OK               0.07s
 69/206 picolibc:headers / check-cdef-stdint.h                      OK               0.07s
 70/206 picolibc:headers / check-cdef-stdnoreturn.h                 OK               0.06s
 71/206 picolibc:headers / check-cdef-stdlib.h                      OK               0.06s
 72/206 picolibc:headers / check-cdef-string.h                      OK               0.06s
 73/206 picolibc:headers / check-cdef-strings.h                     OK               0.05s
 74/206 picolibc:headers / check-cdef-threads.h                     OK               0.09s
 75/206 picolibc:headers / check-cdef-time.h                        OK               0.08s
 76/206 picolibc:headers / check-cdef-uchar.h                       OK               0.08s
 77/206 picolibc:headers / check-cdef-unctrl.h                      OK               0.09s
 78/206 picolibc:headers / check-cdef-unistd.h                      OK               0.09s
 79/206 picolibc:headers / check-cdef-utime.h                       OK               0.09s
 80/206 picolibc:headers / check-cdef-w [...]

2024-12-23 20:39 UTC, keith-packard commented
This all looks awesome! We'll need a compiler and qemu instance that we can incorporate into CI for testing before getting this merged though. That means making tarballs that run on Debian unstable (which will run essentially any Linux binaries) that CI can occasionally download. CI caches the container images, so new binaries are only downloaded when the CI configuration changes. Let me know if you can't find a place to host them and we can dump them on a server I've got at OSU OSL.

2024-12-27 22:25 UTC, FlyGoat commented
@keith-packard Thanks for the feedback! I attempted to get CI jobs working on my side but found it frequently have problems on pulling artefacts from maps.altusmetrum.org, sometimes it's certification problem, sometimes it's timeout in middle...

```
2024-12-27T22:09:55.3138123Z #7 111.1 --2024-12-27 22:09:55--  https://maps.altusmetrum.org/m68k-unknown-elf.tar.xz
2024-12-27T22:09:55.6327301Z #7 111.1 Resolving maps.altusmetrum.org (maps.altusmetrum.org)... 140.211.9.9
2024-12-27T22:09:55.7342739Z #7 111.4 Connecting to maps.altusmetrum.org (maps.altusmetrum.org)|140.211.9.9|:443... connected.
2024-12-27T22:09:55.7343980Z #7 111.5 ERROR: The certificate of 'maps.altusmetrum.org' is not trusted.
2024-12-27T22:09:55.7344566Z #7 111.5 ERROR: The certificate of 'maps.altusmetrum.org' has expired.
2024-12-27T22:09:55.7345840Z #7 111.5 The certificate has expired
```

So I attempted to reproduce tools used here with github action and delivering artefacts with github release, this resulted side project: https://github.com/FlyGoat/picolibc-ci-tools, which build toolchains and qemu automatically and upload to github release on any github tag.

I wonder if it's possible to pull this project to picolibc organisation on github, I think it can ease pressure on your server, as well as improve reproducibility of CI jobs.

2024-12-27 22:29 UTC, FlyGoat commented
I'm not really sure if there are any modification to QEMU source in `qemu-arm` and `qemu-m68k` so I didn't build them for qemu-stable, but it should be straightforward to add extra targets or even QEMU variants.

Also, I'm planning to get lm32 and or1k build tested (for litex project), so I built toolchains for them as well.

2024-12-27 23:34 UTC, keith-packard commented
> So I attempted to reproduce tools used here with github action and delivering artefacts with github release, this resulted side project: https://github.com/FlyGoat/picolibc-ci-tools, which build toolchains and qemu automatically and upload to github release on any github tag.

What a good plan. I've done something temporary to work around this issue -- I've uploaded all of the existing tarballs to https://github.com/picolibc/toolchains so that we can at least get things working. Your plan of actually building them using github CI is better, but that will take some time to make sure we get the right bits built with the right options. Most of those bits have local bug fixes, some of which haven't been released upstream yet. All of this is in PR #899 

> I wonder if it's possible to pull this project to picolibc organisation on github, I think it can ease pressure on your server, as well as improve reproducibility of CI jobs.

Yes, absolutely. We can transition away from the above hack to auto-built toolchains as we get them working. For now,
let's just get your loongarch qemu bits split into a separate file so we can add that to the CI without affecting other qemu bits there.

2024-12-28 00:08 UTC, FlyGoat commented
Currently only qemu-system-loongarch64 is built into qemu-stable tarball :-)

I’m waiting CI to pass in my tree: https://github.com/FlyGoat/picolibc/actions/runs/12521217442

2024-12-28 06:18 UTC, keith-packard commented
ok, I've fixed CI so it pulls toolchain bits from github now. If you'll rebase, I can let CI run on the result and you should be able to get things tested and ready for integration.

2024-12-28 09:13 UTC, FlyGoat commented
@keith-packard Thanks! done.

2024-12-28 20:01 UTC, keith-packard requested changes
couple of fixes needed, but looks really nice

2024-12-28 20:54 UTC, FlyGoat commented on newlib/libc/machine/loongarch/machine/_fpmath.h
> +		uint64_t	manl	:64;
I just blindly copied that from RISC-V, AFAIK there is no MSB mode, should I remove it?

2024-12-28 20:55 UTC, FlyGoat commented on newlib/libc/machine/loongarch/machine/fenv-fp.h
> +  unsigned int fcsr;
It’s always 32bit. Will try uint32_t.

2024-12-28 20:57 UTC, FlyGoat commented on newlib/libc/machine/loongarch/machine/fenv-fp.h
> +__declare_fenv_inline(int) feraiseexcept(int excepts)
I guess other libc do that with trapping in mind. Is it possible that RTOS using picolibc wants trapping?

2024-12-28 22:48 UTC, keith-packard commented on newlib/libc/machine/loongarch/machine/fenv-fp.h
> +__declare_fenv_inline(int) feraiseexcept(int excepts)
Yes, and that might be nice to have, so perhaps you should include this stuff. Then we can treat all of the other archs as faulty :-)

2024-12-28 22:49 UTC, keith-packard commented on newlib/libc/machine/loongarch/machine/fenv-fp.h
> +  unsigned int fcsr;
Yeah, reading the API specs, all of these functions use 'int' parameters anyways; perhaps it's better to just use 'int' everywhere and avoid a pile of unnecessary casts. int is always 32-bit on loongarch, I assume?

2024-12-28 22:50 UTC, keith-packard commented on newlib/libc/machine/loongarch/machine/_fpmath.h
> +		uint64_t	manl	:64;
If the target is always LSB, then, yeah, would be nice to not have MSB confusing people (like me).

2024-12-28 22:53 UTC, FlyGoat commented on newlib/libc/machine/loongarch/machine/fenv-fp.h
> +  unsigned int fcsr;
That’s true from LoongArch ABI convention :-)

2024-12-29 14:04 UTC, FlyGoat commented on newlib/libc/machine/loongarch/machine/_fpmath.h
> +		uint64_t	manl	:64;
I just double-checked current implementation and I think it's already LSB only?

2024-12-30 00:21 UTC, keith-packard commented on newlib/libc/machine/loongarch/machine/_fpmath.h
> +		uint64_t	manl	:64;
sounds good.

2024-12-30 01:05 UTC, FlyGoat commented on newlib/libc/machine/loongarch/machine/fenv-fp.h
> +  unsigned int fcsr;
Opps, seems like something went wrong here, will investigate.

2024-12-30 11:44 UTC, FlyGoat commented on newlib/libc/machine/loongarch/machine/fenv-fp.h
> +  if ((round & ~FE_RMODE_MASK) != 0)
So this check is actually necessary. See MIPS's implementation.

2024-12-30 18:32 UTC, keith-packard commented on newlib/libc/machine/loongarch/machine/fenv-fp.h
> +  if ((round & ~FE_RMODE_MASK) != 0)
Arm and aarch64 also check for invalid parameters. Thanks!

2024-12-31 02:18 UTC, keith-packard commented on newlib/libc/machine/loongarch/asm.h
> +   This copyrighted material is made available to anyone wishing to use,
Could you replace this license text with the text used in newlib/libc/machine/loongarch/machine/fenv.h? 'The FreeBSD license' isn't well defined.

2024-12-31 02:21 UTC, keith-packard requested changes
I was just doing a final pass over the PR before pushing and discovered that newlib/libc/machine/loongarch/asm.h has an ambiguous license. You've used the standard 3-clause BSD license in most of the other new code; can you apply that to this file? If not, can you replace the reference to opensource.org/licenses with the actual license text?

2024-12-31 02:36 UTC, FlyGoat commented
> I was just doing a final pass over the PR before pushing and discovered that newlib/libc/machine/loongarch/asm.h has an ambiguous license. You've used the standard 3-clause BSD license in most of the other new code; can you apply that to this file? If not, can you replace the reference to opensource.org/licenses with the actual license text?

Done! It was a bind copy :-)

2024-12-31 04:09 UTC, merged